name: 'Custom Github Action'
inputs:
  num:
    description:  'Enter Number'
    required: true
    default: "1"
outputs:
  num_squared:
    description: 'Square of the input'
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
